### ISSUE TITLE
Reduce white flashes when opening new blank tabs or while navigating

### ISSUE THREAD

**Issue by NintendoManiac64** [FranklinDM/Swarth#11]
On v1.0.7, when loading a new blank tab or when navigating to https://phoronix.com, you do not get any sort of white flash at all.

On v1.0.8 and v1.0.9, loading a new blank tab or navigating to https://phoronix.com results in a white flash before Swarth "kicks in."

**Comment by fofajardo** [comment]
@NintendoManiac64 can you check if this is still a problem in [v1.0.10a1](https://github.com/FranklinDM/Swarth/releases/tag/v1.0.10a1)?

**Comment by NintendoManiac64** [comment]
It is indeed still an issue in v1.0.10a1

**Comment by fofajardo** [comment]
@NintendoManiac64 can you check if this is still a problem in [v1.1.0a1](https://github.com/FranklinDM/Swarth/releases/tag/v1.1.0a1)?

**Comment by NintendoManiac64** [comment]
Seems to be fixed in v1.1.0a1, at least in the two scenarios I mentioned on this issue.

**Comment by fofajardo** [comment]
Good to know, thanks!
