### ISSUE TITLE
Stuck with default colors on a fresh installation if you change colors and set "Retain page style" at the same time

### ISSUE THREAD

**Issue by NintendoManiac64** [FranklinDM/Swarth#2]
1. do a fresh install of v1.0.4 and restart your browser

2. load some webpage in a new tab (you can use this very github issue page you're currently reading)

3. open swarth's preferences and set custom colors for at least (I haven't tried the others) "unvisited links" and "visited links" by manually typing in a value (e.g. I used "#ffcccc" and "#ccccff") - do NOT click "OK"

4. before clicking OK, set the 'Default color method' to "Retain page style"

5. click OK.

6. without loading any other webpage, look at the tab you previously loaded from step 2 (e.g. this current github issue page)

From there, no matter if you then try changing the 'Default color method' setting to anything else, any webpage from _any_ domain in any tab will always be stuck with the default visited and unvisited color links.

This issue only resolves itself if you either change the colors again or restart the browser.

**Comment by fofajardo** [comment]
Please confirm if the latest release ([v1.0.5](https://github.com/FranklinDM/Swarth/releases/tag/v1.0.5)) resolves this issue.

**Comment by NintendoManiac64** [comment]
Yup, everything seems to be working now.
