### ISSUE TITLE
Unable to Adjust Colours with Palette Selector

### ISSUE THREAD

**Issue by iwakuraSSBM** [FranklinDM/Swarth#3]
OS: Debian
Browser: Palemoon Version 29.4.4 (64-bit)
Swarth Version 1.0.5

Opening Swarth preferences allows me to interact normally with the Swarth preferences window, I can update a colour code in the box manually. However, when I click on a colour to update it via the colour selection window, that window pops up but is completely frozen.

Nothing will close it unless I go back to the Swarth preferences window and close that. 

I'm not sure how you invoke this colour selection tool, but I must assume it's a palemoon tool and not something that you have added yourself. Either way I felt it was important for you to know this issue is happening, at least on the Linux version of palemoon. 

If you'd like additional information or logs please instruct me on how I can generate that for you.

**Comment by fofajardo** [comment]
Confirmed.

The hang seems to be only happening if the HTML5 color picker is invoked from XUL. If it is used from a regular web page, there doesn't seem to be a problem. I'll see what I can do about this.

EDIT: Oddly-enough, this seems to only occur with Swarth's preferences window. I've tried inserting a color picker with PTXE and it works. Hmmm.

**Comment by fofajardo** [comment]
Most likely a platform issue, bug describing the same problem: [bug 1496836](https://bugzilla.mozilla.org/show_bug.cgi?id=1496836)

Should be fairly straightforward to backport.

**Comment by fofajardo** [comment]
For now, I've implemented a workaround by making the extension not launch the preferences window as modal.
